baseurl: /
permalink: /:title.html
auto: true
markdown: rdiscount
paginate: 10
highlighter: pygments


author: KimmyKuang
title: KimmyKuang's Blog
email: kimmykuang@hotmail.com
github: https://github.com/kimmykuang
